stages:
  - test
  - deploy
  - docs
  - publish

before_script:
  # display centos version
  # - cat /etc/issue

  # Pull required packages
  - python3 -m pip install --user -r requirements.txt
  - python3 -m pip install --user -r requirements-test.txt
  - python3 -m pip install --user -r doc/requirements.txt
  # - python3 -m pip install pytest pytest-cov
  - python3 -m pip list

pytest:
  stage: test
  timeout: 20m
  script:
    - python3 -m pytest --cov=configparserenhanced --cov-report=html --cov-report=term --cov-config=.coveragerc
  coverage: '/TOTAL\s*\d+\s+\d+\s+\d+\s+\d+\s+(\d+%)/'

apptest:
  stage: test
  timeout: 10m
  script:
    - cd examples/
    - python3 ./ConfigParserEnhanced-example-01.py

install:
  stage: deploy
  needs: [pytest]
  timeout: 20m
  script:
    - python3 -m pip install --user .
    - python3 -m pip uninstall -y configparserenhanced

sphinx-documentation:
  stage: docs
  needs: [install]
  timeout: 20m
  script:
    - cd doc/
    # - python3 -m pip install -r requirements.txt
    - bash make_html_docs.sh

publish coverage:
  stage: publish
  needs: [pytest]
  timeout: 20m
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - python3 -m pytest --cov=configparserenhanced --cov-report=html --cov-report=term --cov-config=.coveragerc
    - rm -rf /home/josbrau/html_files/ConfigParserEnhanced/coverage
    - mkdir -p /home/josbrau/html_files/ConfigParserEnhanced/coverage
    - mv tests/htmlcov/* /home/josbrau/html_files/ConfigParserEnhanced/coverage/

publish docs:
  stage: publish
  needs: [sphinx-documentation]
  timeout: 20m
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - cd doc/
    # - python3 -m pip install -r requirements.txt
    - bash make_html_docs.sh
    - rm -rf /home/josbrau/html_files/ConfigParserEnhanced/doc
    - mkdir -p /home/josbrau/html_files/ConfigParserEnhanced/doc
    - mv html/* /home/josbrau/html_files/ConfigParserEnhanced/doc/


